# Generated by Django 5.0.3 on 2024-03-17 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Carousel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to='ima')),
                ('title', models.CharField(max_length=250)),
                ('subtitle', models.CharField(max_length=250)),
            ],
        ),
    ]
